
[mediaTypes."text/vcard"]
suffixes = ["vcf"]
charset = "utf-8"

[outputFormats.VCARD]
mediaType = "text/vcard"
isPlainText = true
baseName = "contact"

[outputs]
page = ["HTML", "VCARD"]
section = ["HTML"]
home = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]
