baseURL = 'https://synergy-services.github.io/'
languageCode = 'en-us'
title = 'Synergy Services Co .Ltd'

[taxonomies]
  service = 'services'
  team = 'team'
  partner = 'partners'
  project = 'projects'
  blog = 'blogs'
  timeline = 'timelines'

[params]
  dateFormat = "02 Jan 2006"
  yearFormat = "2006"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
